services:
  web:
    ports:
      - 5000:3000
      - 24678:24678
    volumes:
      - ./data:/data
      - ./app/src:/app/src
      - ./app/static:/app/static
  server:
    ports:
      - 3000:3000
  db:
    ports:
      - 5432:5432
